-- ============================================================
-- 0034_intelligence.sql
-- AI & intelligence layer:
--
--   ai_digests          : weekly AI business digest (Monday brief)
--   churn_alerts        : AI-flagged cooling customers + drafted
--                         win-back message
--   competitors         : competitor watch list
--   competitor_entries  : logged observations (price/post/ad/news)
--                         + monthly AI summary on the competitor
--   ad_entries          : Meta/Google ad spend & results next to revenue
--   visitor_events      : website visitor intelligence (pageviews,
--                         form starts/abandons/submits) captured by the
--                         public /api/public/track snippet
-- ============================================================

-- ---- Weekly AI digest ---------------------------------------
create table if not exists public.ai_digests (
  id         uuid primary key default gen_random_uuid(),
  -- Monday of the week the digest covers.
  week_start date not null,
  -- Markdown body shown in the app (and reusable in email/SMS).
  content    text not null default '',
  -- Raw numbers the digest was computed from (leads, invoices, …).
  stats      jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create unique index if not exists ai_digests_week_idx on public.ai_digests (week_start);

-- ---- Churn / cold-customer alerts ---------------------------
create table if not exists public.churn_alerts (
  id            uuid primary key default gen_random_uuid(),
  client_id     uuid references public.clients (id) on delete cascade,
  client_name   text not null default '',
  severity      text not null default 'warm'
                check (severity in ('cooling', 'warm', 'cold')),
  reason        text not null default '',
  -- AI-drafted win-back message, editable before sending.
  draft_message text,
  status        text not null default 'open'
                check (status in ('open', 'actioned', 'dismissed')),
  created_at    timestamptz not null default now()
);

create index if not exists churn_alerts_status_idx on public.churn_alerts (status, created_at desc);

-- ---- Competitor watch ---------------------------------------
create table if not exists public.competitors (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  website       text,
  facebook      text,
  instagram     text,
  notes         text,
  ai_summary    text,
  ai_summary_at timestamptz,
  created_by    uuid references public.profiles (id) on delete set null default auth.uid(),
  created_at    timestamptz not null default now()
);

create table if not exists public.competitor_entries (
  id            uuid primary key default gen_random_uuid(),
  competitor_id uuid not null references public.competitors (id) on delete cascade,
  kind          text not null default 'note'
                check (kind in ('price', 'post', 'ad', 'news', 'note')),
  content       text not null,
  created_by    uuid references public.profiles (id) on delete set null default auth.uid(),
  created_at    timestamptz not null default now()
);

create index if not exists competitor_entries_idx
  on public.competitor_entries (competitor_id, created_at desc);

-- ---- Ads performance ----------------------------------------
create table if not exists public.ad_entries (
  id           uuid primary key default gen_random_uuid(),
  platform     text not null default 'meta'
               check (platform in ('meta', 'google', 'tiktok', 'other')),
  campaign     text not null,
  period_start date not null,
  period_end   date not null,
  spend        numeric(14, 2) not null default 0,
  currency     text not null default 'LKR',
  impressions  integer,
  clicks       integer,
  leads        integer,
  revenue      numeric(14, 2),
  notes        text,
  created_by   uuid references public.profiles (id) on delete set null default auth.uid(),
  created_at   timestamptz not null default now()
);

create index if not exists ad_entries_period_idx on public.ad_entries (period_start desc);

-- ---- Website visitor intelligence ---------------------------
create table if not exists public.visitor_events (
  id         uuid primary key default gen_random_uuid(),
  -- Which site the event came from (the snippet's data-site value).
  site       text not null default 'default',
  -- Anonymous per-browser session id generated by the snippet.
  session_id text not null,
  kind       text not null default 'pageview'
             check (kind in ('pageview', 'form_start', 'form_abandon', 'form_submit', 'click')),
  path       text not null default '/',
  referrer   text,
  -- { form_id?, field?, label?, seconds_on_page?, … }
  meta       jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists visitor_events_site_idx
  on public.visitor_events (site, created_at desc);
create index if not exists visitor_events_session_idx
  on public.visitor_events (session_id, created_at);

-- ---- RLS + realtime -----------------------------------------
-- visitor_events rows are inserted by the public track endpoint through
-- the service-role client; authenticated users only read them.
do $$
declare t text;
begin
  foreach t in array array[
    'ai_digests', 'churn_alerts', 'competitors', 'competitor_entries',
    'ad_entries', 'visitor_events'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    begin
      execute format('create policy "%s: read all" on public.%I for select to authenticated using (true)', t, t);
    exception when duplicate_object then null; end;
    begin
      execute format('create policy "%s: insert all" on public.%I for insert to authenticated with check (true)', t, t);
    exception when duplicate_object then null; end;
    begin
      execute format('create policy "%s: update all" on public.%I for update to authenticated using (true) with check (true)', t, t);
    exception when duplicate_object then null; end;
    begin
      execute format('create policy "%s: delete all" on public.%I for delete to authenticated using (true)', t, t);
    exception when duplicate_object then null; end;
    begin
      execute format('alter publication supabase_realtime add table public.%I', t);
    exception when others then null; end;
  end loop;
end $$;
